title: Masatoshi Nishiguchi
description: Maintainable Web Development using Ruby, Rails and React.
permalink: pretty
url: "https://mnishiguchi.com"
baseurl: ""
author:
  name: Masatoshi Nishiguchi
  email: nishiguchi.masa@gmail.com
sass:
  sass_dir: _sass  # the directory that contains sass partials
  style: :compressed
include:
  - _pages
  - _redirects
exclude:
  - node_modules
  - admin/index.js
plugins:
  - jekyll-gist
  - jekyll-paginate
navigation_links:
  - [Home, /]
  - [Posts, /posts]
  - [About, /about]
social_links:
  - [github, "https://github.com/mnishiguchi"]
  - [linkedin, "https://linkedin.com/in/mnishiguchi"]
  - [stack-overflow, "https://stackoverflow.com/users/3837223/mnishiguchi"]
paginate: 2
excerpt_separator: "\n\n\n" # two blank lines
read_more_text: "read more »"
empty_array: []
